CREATE TABLE PURCHASE(ID INTEGER PRIMARY KEY AUTO_INCREMENT, ACCOUNT VARCHAR(20) NOT NULL, DATE DATE NOT NULL, AMOUNT INTEGER NOT NULL, CATEGORY VARCHAR(20) NOT NULL, SHOP VARCHAR(50) NOT NULL, SUBJECT VARCHAR(50) NOT NULL, COMMENT TEXT NOT NULL, FILES VARCHAR VARCHAR*=(500));

